### ISSUE TITLE
Not supported on SDK 8

### ISSUE THREAD

**Issue by ffMathy** [appcelerator-archive/ti.inappbilling#34]
I can't get this working on Appcelerator SDK 8 RC.

**Comment by jkotchoff** [comment]
Same. @hansemannn, are there any plans to introduce 8.0.0.GA support for this module?

**Comment by jkotchoff** [comment]
Hans, apologies if this is pulling you into something you no longer support - I forgot you are no longer with Appcelerator.

**Comment by m1ga** [comment]
Is there any error? It is compiled for 7.x so it should work in 8, too. Unless there are any errors when using it

**Comment by hansemannn** [comment]
Probably the updated play-services. We can work on this, but it'd need to be quoted.

**Comment by jkotchoff** [comment]
This is a pretty crucial module so updating for play-services seems pretty important. What's involved in getting it 'quoted'?

**Comment by m1ga** [comment]
@jkotchoff I have to ask again: what error do you get? I can compile the current 5.0.0 module fine with Ti SDK 8.0.0. I don't "use" it besides requiring it so I can't test any functionality. But compiling works fine.

@hansemannn it looks like it doesn't use any external libraries

**Comment by jkotchoff** [comment]
Sorry guys, this was my mistake. I believe this module is working correctly for Ti SDK 8.0.0 when it sits alongside version 16.1.2 of ti.playservices. In my case, the error I was seeing was actually coming from a different module (ti.admob). I think this issue can probably be closed and one needs to be opened for ti.admob instead. Apologies again.

**Comment by AppWerft** [comment]
this inappbilling can work with playservice or with aidl. The Titanium  module uses aidl and don't need external libraries.

**Comment by AppWerft** [comment]
The method `queryInventory()` seems to contain the result of getPurchases(). Not sure. There is a ticket about it. https://jira.appcelerator.org/browse/MOD-2494

Maybe `getPurchaseHistory()` is missing.

**Comment by deckameron** [comment]
I am getting this error when using it with SDK 8.0.0 on android 9 device.
The error does not happen on Android 8 or 7 devices.
```javascript
05-06 15:33:47.029: E/AndroidRuntime(12807): FATAL EXCEPTION: main
05-06 15:33:47.029: E/AndroidRuntime(12807): Process: com.douglas.test, PID: 12807
05-06 15:33:47.029: E/AndroidRuntime(12807): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8titanium13TypeConverter18javaLongToJsNumberEPN2v87IsolateEx" referenced by "/data/app/com.douglas.test-yu0XAW6GgEtd5GvmHnEiDg==/lib/arm64/libti.inappbilling.so"...
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at java.lang.System.loadLibrary(System.java:1669)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:131)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:105)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:167)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:109)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at com.douglas.test.TestApplication.onCreate(TestApplication.java:318)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at android.os.Looper.loop(Looper.java:193)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at java.lang.reflect.Method.invoke(Native Method)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-06 15:33:47.029: E/AndroidRuntime(12807): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by deckameron** [comment]
[This](https://github.com/appcelerator-archive/ti.inappbilling/issues/35#issuecomment-485009528) solves the issue.

**Comment by jkotchoff** [comment]
According to Appcelerator, this module is not supported anymore:
https://jira.appcelerator.org/browse/MOD-2526

**Comment by AppWerft** [comment]
Maybe this helps you: https://github.com/AppWerft/ti.inappbilling

**Comment by hansemannn** [comment]
We just finished developing a new version of Play Billing (the modern alternative to the deprecated AIDL billing that is used here). It is written in modern Kotlin, supports all kind of subscriptions and has extensive docs and example code around it. You can find more details [here](https://github.com/hansemannn/titanium-play-billing-demo)!
