### ISSUE TITLE
Does not work, throws an error on startIntentSenderForResult

### ISSUE THREAD

**Issue by dereklucas** [appcelerator-archive/ti.inappbilling#4]
I am getting the below error when trying to make purchases. I am using titanium SDK 3.3.0 and the Android version on device is running 4.0.3. I added to the android manifest:

```
<android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest>
        <uses-permission android:name="com.android.vending.BILLING" />
        </manifest>
     </android>
```

Error:

```
[INFO] :   queryInventory
[INFO] :   Query Inventory response: OK
[INFO] :   subscriptionsSupported: true
[INFO] :   queryInventory
[INFO] :   Query Inventory response: OK
[INFO] :   purchase gas
[INFO] :   dalvikvm: Could not find method android.app.Activity.startIntentSenderForResult, referenced from method org.appcelerator.titanium.util.TiActivitySupportHelper.launchIntentSenderForResult
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 146: Landroid/app/Activity;.startIntentSenderForResult (Landroid/content/IntentSender;ILandroid/content/Intent;IIILandroid/os/Bundle;)V
[DEBUG] :  dalvikvm: VFY: replacing opcode 0x74 at 0x0016
[WARN] :   W/System.err: java.lang.NoSuchMethodError: android.app.Activity.startIntentSenderForResult
[WARN] :   W/System.err:    at org.appcelerator.titanium.util.TiActivitySupportHelper.launchIntentSenderForResult(TiActivitySupportHelper.java:92)
[WARN] :   W/System.err:    at org.appcelerator.titanium.TiBaseActivity.launchIntentSenderForResult(TiBaseActivity.java:615)
[WARN] :   W/System.err:    at ti.inappbilling.util.IabHelper.launchPurchaseFlow(IabHelper.java:425)
[WARN] :   W/System.err:    at ti.inappbilling.InappbillingModule.purchase(InappbillingModule.java:219)
[WARN] :   W/System.err:    at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN] :   W/System.err:    at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:64)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:884)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1107)
[WARN] :   W/System.err:    at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:347)
[WARN] :   W/System.err:    at ti.modules.titanium.ui.TableViewProxy.handleMessage(TableViewProxy.java:942)
[WARN] :   W/System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN] :   W/System.err:    at android.os.Looper.loop(Looper.java:154)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  TiExceptionHandler: (main) [33724,33724] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [1,33725] - In app.js:89,26
[ERROR] :  TiExceptionHandler: (main) [3,33728] - Message: Uncaught Error: android.app.Activity.startIntentSenderForResult
[ERROR] :  TiExceptionHandler: (main) [1,33729] - Source:             InAppBilling.purchase({
[ERROR] :  V8Exception: Exception occurred at app.js:89: Uncaught Error: android.app.Activity.startIntentSenderForResult
```

Any ideas? I've seen other people with this same problem dating back several weeks, but I can't find any solutions at all.. or even anything pointing in the right direction!

**Comment by bitshftr** [comment]
Was this ever fixed?  Did anyone find a solution?

**Comment by Geek-Fish** [comment]
I haven't yet and I think this is happening with some versions of Android 5 also. I've had a few people email me and say that purchasing and restoring isn't working on Samsung S5/S6, but I don't have one to test with.

**Comment by spudz000** [comment]
I also have the same problem on both 4.0.4. and 3.2 honeycomb.  Not sure what to do here?

**Comment by Geek-Fish** [comment]
I think development has stopped on this module. I haven't been able to find
a suitable replacement nor do I have the time or skill to fix this (it's
been awhile since I've Java'ed). Might be time for me to look into more
though, I need to get this fixed.
